---
layout: post
title: Django and mysterious 500
date: 2020-07-05
description: The short note about how to fix Error 500 when you use NGINX Unit with Django.
published: true
---

This issue appeared in our project where we use dockerized Django, Nginx, and NGINX Unit.

When saving data in Django admin, error 500 occurs:

```html
<!DOCTYPE html>
   <title>Error 500</title>
<p> Error 500.
```

Since the request is interrupted by an error even before it reaches the Django's middlewares, `Nginx`, and `Unit` becoming the main suspects.

Let's try to change the value of the parameter `client_max_body_size` of `Nginx`. Did not helped.

Let's look at the logs of the container with `Django` and application server (`Unit`):

```
# ...
# ...
2020/07/16 09:25:35 [error] 28#39 *18 mkstemp() failed (2: No such file or directory)
# ...
```

The Unit tries to create a temporary file when the size of the request body exceeds a certain limit and first writes the body of the request to this temprary file and then reads it, but in our case, the creation for some reason fails. Most often, such errors are related to permissions, so we climb to look at the value of the `--tmp` parameter in` help` and see the following:

```
--tmp DIRECTORY      set tmp directory name default: "/usr/tmp"
```

This is where all the problems come from. For security reasons, Django is not run as root, and `/usr /tmp` is a directory owned by the root user and for this is why an error occurs. To solve the issue, just pass the parameter `--tmp` with right value to the `Unit`:

`unitd --tmp /tmp ...`

The only question is why the `Unit` for `Alpine` is set to `--tmp /usr/tmp` by default. Personally, I have no ideas, but it is possible that there are reasons for this...
